### ISSUE TITLE
Handle step return

### ISSUE THREAD

**Issue by xusheng6** [Vector35/debugger_native#1]
Zain and I explored several ways to implement the step return, but none of them seem always reliable. We might need to support stepping return using different strategies

**Comment by CouleeApps** [comment]
For reference, here were a few of the ways debated on the python debugger:

- Breakpoint on all ret instructions and continue, then clear those breakpoints. This only works if you have analysis data. This is what was implemented
- Read the stack return address and breakpoint on that. This is way faster and works even without analysis data, but may be incorrect in weird code.
- Some combination of the two, except check the stack pointer and try to handle recursion properly (try the fibbonaci test case)

My best guess is this is not solvable in the general case, but any of those options should be good enough for regular use.

**Comment by xusheng6** [comment]
I implemented the "find return addresses and break" strategy. We will later improve another approach for it, i.e., walk the stack, find the return address, and break on it. Consider open another issue then.
