### ISSUE TITLE
Lost disassembly view in debugger - not sure how to get it back.

### ISSUE THREAD

**Issue by angrygoats** [Vector35/debugger_native#58]
Hey - 

Really like the debugger so far but I think I've broken it in a way I can't immediately see how to fix. I fired up an executable and originally it would display the disassembly view next to the debugger memory output. But I cannot get it to return even if I turn on reflections. Attached is an image: 

![image](https://user-images.githubusercontent.com/11184919/124714426-9a5afb00-deb6-11eb-9bc0-973e9a899fc1.png)

Unfortunately there seems to very little documentation with the debugger so far so I am not sure where to go with this. Is there a way to get my disassembly view to return so I can get back to debugging?

**Comment by xusheng6** [comment]
The native debugger now uses BN's own views, so it is not bothered by this problem.
