### ISSUE TITLE
Support viewing variable values

### ISSUE THREAD

**Issue by tekwizz123** [Vector35/debugger_native#72]
Currently the debugger allows one to step through the program one HLIL instruction at a time, but there is no way that I can tell to view the HLIL variable names within the debugger, which makes this method significantly less useful. Adding support to view HLIL variable names from the debugger and see their values over time would allow for more useful insights and, when combined with API access, could significantly simplify the automation of common work.

**Comment by xusheng6** [comment]
We now annotate the stack variables in the linear view.
