### ISSUE TITLE
Automatically hide/show debugger widgets

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/debugger_native#95]
Currently, when you switch to the debugger, none of the widgets appear and the user has to manually show them all. We should automatically show the relevant debugging widgets when the user switches to the debug view, and hide them when they switch away.

**Comment by xusheng6** [comment]
The widgets are now organized into a debugger sidebar. It is easy enough to toggle it, so I do not think we should force switch to it. The user can simply press the F9 key to launch the target. 

Related to https://github.com/Vector35/debugger_native/issues/46
