### ISSUE TITLE
DebugProcessView is so large it breaks some things

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/debugger_native#97]
Turns out when your view reports itself as 0xffffffffffffffff bytes long, some things stop working

List of known things broken:
- [x] `bv.__len__`
- [ ] LinearView can't scroll to the end
- [x] HexView/LinearView address display width get messy

**Comment by xusheng6** [comment]
Two of the problems are already fixed (by other commits in the UI/API), and the second seems not a huge problem for usability.
